theme: jekyll-theme-hacke
Hello

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=git sta, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Hello</title>
</head>
  
<body>
  <h1>Урок №12 done</h1>
  
</body>
</html>
